### ISSUE TITLE
denying access doesn't return

### ISSUE THREAD

**Issue by ScottChapman** [benkroeger/passport-ibm-connections-cloud#1]
It looks like a loop because the callback route is also protected with authenticate.

See what I mean?

**Comment by benkroeger** [comment]
I get what you mean... but this is not a problem with this module.
The [OAuth 2.0 spec](https://tools.ietf.org/html/rfc6749) clearly describes the provider's behaviour in case of access denial [errors](https://tools.ietf.org/html/rfc6749#section-4.1.2.1) to redirect to the callback url with the query parameter `error=access_denied`. IBM Connections Cloud however, **does not behave like that**. They redirect with the parameter `oauth_error=oauth_denied`... which is why the denial is not detected.

**Comment by benkroeger** [comment]
fixed in [v1.0.2](https://github.com/benkroeger/passport-ibm-connections-cloud/releases/tag/1.0.2)

**Comment by ScottChapman** [comment]
I was able to work around it by providing a handler method BEFORE the passport.authenticate method on the callback route. In that method I can look for the OAUTH failure and handle it myself.

I took a quick scan through your changes, not sure I understood them. DId you attempt to provide corrected behavior in the module?

**Comment by benkroeger** [comment]
Yep, it is fixed in the 1.0.2.
The passport strategy detects the wrongly named error code ignites the "fail" behaviour from passport.
You might want to take a look the [passport](http://passportjs.org/docs/authenticate), specifically the section with custom callbacks.
Also, take a look at passport's authenticate options. Depending on your use-case, it might be better to skip the failureRedirect option and have it respond with a proper 401 instead

**Comment by ScottChapman** [comment]
awesome, I'll take a look at it in the AM. I started trying to implement a custom callback, but wasn't getting the behavior I wanted. I think the flow of events is a little different for an OAUTH2 strategy. I'm a bit new to this, so learning...

**Comment by ScottChapman** [comment]
Confirmed it works! Thanks a ton!
